version: '3.1'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/debian/jenkins/configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
  db:
    image: mariadb:10.6
    container_name: mariadb_container
    networks:
      - "network1"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: BrieucGorin
      MARIADB_DATABASE: cashtagdb
    volumes:
      - /home/debian/var-lib-mysql/:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    networks:
      - "network1"
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - db

  backend:
    image: dailymon:latest
    networks:
      - "network1"
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    image: dailyvue:latest
    networks:
      - "network1"
    ports:
      - 80:80
    depends_on:
      - backend

networks:
  network1:
    name: network1
    driver: bridge