spring:
  datasource:
    url: jdbc:mariadb://mariadb_container:3306/dailymondb
    username: root
    password: BrieucGorin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

#spring:
#  liquibase:
#    enabled: true

#server:
#  port: 8090