spring:
  datasource:
    url: jdbc:mariadb://mariadb_container:3306/dailymondb
    username: root
    password: BrieucGorin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml  

security:
  require-ssl: true

server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/vps-4ac2e447.vps.ovh.net/keystore.p12
    key-store-password: Thunder1982fr_
    key-store-type: PKCS12
    key-alias: tomcat